server:
  port: 8080
  servlet:
    context-path: /artemis
spring:
  jms:
    pub-sub-domain: false
  artemis:
    mode: native
    broker-url: tcp://127.0.0.1:61616
    user: artemis
    password: artemis