spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb
    username: root
    password: 270503
  jpa:
    properties:
      #hibernate.generate_statistics: true
      hibernate:
        format_sql : true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update   # Hibernate ddl auto (create, create-drop, update)
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true