# Pulsar 服务URL
spring.pulsar.client.service-url=pulsar://192.168.5.181:6650

# 可选配置
# spring.pulsar.client.operation-timeout=30s
# spring.pulsar.client.connection-timeout=10s
# spring.pulsar.client.request-timeout=60s
